### ISSUE TITLE
умова відбору

### ISSUE THREAD

**Issue by pecourses** [BohdanLuts/home-work-lesson-52-sequelize-model#1]
https://github.com/BohdanLuts/home-work-lesson-52-sequelize-model/blob/e9a4f5c07e50a3ee32ca8c18313f659c2828ca4f/index.js#L62
- старше 2020 року випуску - це випущені раніше 2020 року, тобто старші за віком

**Comment by BohdanLuts** [comment]
Виправлено на:
year: {
        [Sequelize.Op.lt]: 2020,
      },
 де ".lt" - оператор "менше ніж"
